# Site settings
name: John Crisostomo 
title: John Crisostomo | Software Engineer
description: Full-stack software generalist with experience in analog electronics
url: https://johncrisostomo.com/
baseurl: ""
email: johncrisostomo@protonmail.ch
cover: https://johncrisostomo.com/img/og.png
logo: https://johncrisostomo.com/img/emojis/technologist.png
social:
  - title: email
    url: mailto:johncrisostomo@protonmail.ch
  - title: twitter
    url: https://twitter.com/johncrisostomo
  - title: codepen
    url: http://codepen.io/johncrisostomo
  - title: github
    url: https://github.com/johncrisostomo
  - title: linkedin
    url: https://www.linkedin.com/in/johncrisostomo

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
